server:
  port: 8080
  compression:
    enabled: true

#db정보
spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/project?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234!@#$abcd
  mvc:
    converters:
      preferred-json-mapper: gson

mybatis:
  mapper-locations: classpath:mapper/**/*.xml